### PR TITLE
Tweak wording on graphics

### LINKED ISSUE #10: New logos and share images
Anant has sent through new headers and share images that say 'track' instead of 'report' - can we switch them in?

### PR DESCRIPTION
**Pull request by andylolz**
~~INCOMPLETE. fb_pledge_share.png still needs updating.~~ UPDATE: this is ready now! :)

Fixes #10.

### CODE REVIEW

**Comment by osahyoun** [comment]
What if we go with this for now? @andylolz  @hannamade

**Comment by hannamade** [comment]
Go with what? I'm not sure I understand this.

**Comment by andylolz** [comment]
Hi @hannamade – so [if you go here](https://github.com/osahyoun/istreetwatch/pull/12/files) you can see the changes made in this pull request. Only images have changed – The old versions are on the left (with “report racism & xenophobia”); the new ones on the right (with “track racism & xenophobia”).

The only problem is the new facebook share image is a bit small. It’s not a big problem, but I’ll email Anant back about this now.

**Comment by osahyoun** [comment]
Would be good to get that FB share image corrected before merging this.

**Comment by andylolz** [comment]
> Would be good to get that FB share image corrected before merging this.

Okay – updated now, thanks to Anant. The new image is a jpg rather than a png, but I don’t think anything else needs to change for that to work.

**Comment by hannamade** [comment]
Thank you!!

**Comment by osahyoun** [comment]
👍

**Pull request merged**
